# Build settings
permalink: pretty
markdown: kramdown

# Site settings
title: Stochastic Learnings
email: sergiy.matusevych@gmail.com
github_username: motus

# theme: jekyll-theme-minimal
theme: minima

excerpt_separator: <!-- MORE -->
