# Build settings
permalink: pretty
markdown: kramdown

# Site settings
title: Stochastic Learnings
author: Sergiy Matusevych
email: sergiy.matusevych@gmail.com
github_username: motus

# theme: minima
# theme: jekyll-theme-minimal
theme: jekyll-theme-architect

excerpt_separator: <!-- MORE -->
