# Build settings
permalink: pretty
markdown: kramdown

# Site settings
title: Sergiy Matusevych
email: sergiy.matusevych@gmail.com
github_username: motus

theme: jekyll-theme-hacker
# theme: jekyll-theme-minimal
# theme: minima

excerpt_separator: <!-- MORE -->
