# Build settings
permalink: pretty
markdown: kramdown

# Site settings
title: Sergiy Matusevych
email: sergiy.matusevych@gmail.com
github_username: motus

theme: jekyll-theme-minimal

excerpt_separator: <!-- MORE -->
